/* ============================================================
   cs-demo.jsx — DEMO MODE datasets (extracted from cs-data.jsx)
   Pre-analyzed competitor sets for ?demo=1 client demos: loads
   instantly, no API key / sign-in, so a demo can't fail on quota.

   LOAD ORDER: must load AFTER cs-data.jsx (uses BRANDS,
   socialPlatsFor, THEME_LABELS at init) and BEFORE cs-ui/cs-app
   (which call loadDemoCompetitors).
   ============================================================ */
const _demoImg = (seed) => `https://picsum.photos/seed/${seed}/400/500`;
/* Category-appropriate stock imagery for the creative grid (served via the weserv proxy).
   High-population keywords so they reliably return relevant photos. */
const DEMO_KEYWORDS = {
  alcohol:  ["beer", "cocktail", "bar", "party", "drinks", "cheers"],
  qsr:      ["burger", "fries", "chicken", "pizza", "restaurant", "soda"],
  retail:   ["shopping", "fashion", "store", "product", "delivery", "clothing"],
  telecoms: ["smartphone", "technology", "network", "phone", "city", "connection"],
  beauty:   ["makeup", "cosmetics", "lipstick", "model", "glamour", "mascara"],
  skincare: ["skincare", "serum", "spa", "moisturizer", "face", "cosmetics"],
  haircare: ["hairstyle", "salon", "hair", "model", "shampoo", "beauty"],
};
function _demoPosts(o) {
  const cat = BRANDS[o.parent] ? BRANDS[o.parent].category : o.parent;
  const kws = DEMO_KEYWORDS[cat] || ["product", "lifestyle", "brand", "social", "marketing", "design"];
  const base = Math.abs([...o.name].reduce((a, c) => a + c.charCodeAt(0), 0)) % 900;
  return kws.map((kw, i) => `https://loremflickr.com/400/500/${kw}?lock=${base + i + 1}`);
}
function demoCard(o) {
  const socials = socialPlatsFor(o.parent);
  return {
    name: o.name, handle: o.handle, color: o.color, parent: o.parent, source: "synced", note: "",
    ig: o.ig || "#", fb: o.fb || "#", x: o.x || "#", tiktok: o.tiktok || "", web: o.web || "#",
    snapshot: o.snapshot,
    themes: THEME_LABELS.map(l => ({ label: l, value: o.themes[l] || 0 })),
    insight: o.insight,
    sentiment: o.sentiment,
    postFrequency: Object.fromEntries(socials.map(p => [p, o.freq[p] || 0])),
    effectivenessScore: o.score,
    executiveSummary: o.exec || "",
    keyCampaigns: o.campaigns || [],
    contentSnapshot: o.content || null,
    creativeScores: o.creative,
    whitespace: o.whitespace || "",
    recommendations: o.rec || "",
    signalMatch: !!o.signalMatch, signalNote: o.signalNote || "", signalLink: o.signalLink || "",
    posts: o.posts || _demoPosts(o),
    analyzing: false, analyzed: true,
  };
}

const DEMO_DATA = {
  qsr: [
    demoCard({ name: "KFC SA", handle: "@kfcsa", color: "#E4002B", parent: "qsr",
      ig: "https://instagram.com/kfcsa", fb: "https://facebook.com/KFCSouthAfrica", x: "https://x.com/KFCSA", tiktok: "@kfcsa", web: "https://kfc.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Always-on value promos" },
        { platform: "Instagram", role: "Primary",  comment: "Bucket culture, music" },
        { platform: "X",         role: "Light",    comment: "Customer care" },
        { platform: "TikTok",    role: "Primary",  comment: "Creator-led trends" },
        { platform: "Website",   role: "Primary",  comment: "Online ordering" } ],
      themes: { Promotions: 78, Product: 60, Serves: 30, Seasonal: 22, Lifestyle: 42 },
      insight: "KFC SA dominated June through always-on value messaging, anchored by the **Streetwise** range and a **#KFCxGqom** creator series that drove the bulk of its TikTok engagement.",
      sentiment: { positive: 68, neutral: 24, negative: 8 }, freq: { Facebook: 22, Instagram: 26, X: 14, TikTok: 30 }, score: 8.4,
      creative: { platformNative: 9, culturalRelevance: 9, visualDistinctiveness: 7, strategicClarity: 8, engagementPotential: 9 },
      exec: "KFC leaned hard into value and culture, pairing the Streetwise range with locally-relevant creator content to defend share among younger, price-sensitive audiences.",
      campaigns: [{ title: "Streetwise Value", description: "Always-on affordability push across all platforms." }, { title: "#KFCxGqom", description: "Creator series tying the brand to local gqom music culture." }],
      whitespace: "Limited premium / quality storytelling — all value, little craft.", rec: "Hunters can own a 'crafted' positioning where KFC stays purely transactional.",
      signalMatch: true, signalNote: "Found a **Streetwise** value-range push dated 9 June running across Instagram and TikTok.", signalLink: "https://instagram.com/kfcsa" }),
    demoCard({ name: "McDonald's SA", handle: "@mcdonaldssa", color: "#FFC72C", parent: "qsr",
      ig: "https://instagram.com/mcdonaldssa", fb: "https://facebook.com/McDonaldsSA", x: "https://x.com/McDonaldsSA", tiktok: "@mcdonaldssa", web: "https://mcdonalds.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Family & value" },
        { platform: "Instagram", role: "Primary",  comment: "Product hero shots" },
        { platform: "X",         role: "Light",    comment: "Reactive banter" },
        { platform: "TikTok",    role: "Light",    comment: "Trend participation" },
        { platform: "Website",   role: "Primary",  comment: "App & delivery" } ],
      themes: { Promotions: 65, Product: 80, Serves: 25, Seasonal: 35, Lifestyle: 20 },
      insight: "McDonald's SA centred June on product hero creative and the **McDelivery** app push, with a polished but less culturally-native feed than KFC.",
      sentiment: { positive: 62, neutral: 28, negative: 10 }, freq: { Facebook: 18, Instagram: 20, X: 9, TikTok: 12 }, score: 7.6,
      creative: { platformNative: 7, culturalRelevance: 6, visualDistinctiveness: 8, strategicClarity: 8, engagementPotential: 7 },
      exec: "Product-led and app-first, McDonald's prioritised polish and delivery conversion over cultural relevance this period.",
      campaigns: [{ title: "McDelivery", description: "App-led delivery convenience messaging." }],
      whitespace: "Under-indexed on local culture and creators vs KFC.", rec: "Cultural relevance is contestable territory against McDonald's.",
      signalMatch: false, signalNote: "No matching content found." }),
    demoCard({ name: "Burger King SA", handle: "@burgerkingsa", color: "#D62300", parent: "qsr",
      ig: "https://instagram.com/burgerkingsa", fb: "https://facebook.com/BurgerKingSA", x: "https://x.com/BurgerKingZA", tiktok: "@burgerkingsa", web: "https://burgerking.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Price-led offers" },
        { platform: "Instagram", role: "Primary",  comment: "Flame-grill craft" },
        { platform: "X",         role: "Light",    comment: "Challenger jabs" },
        { platform: "TikTok",    role: "Light",    comment: "Occasional trends" },
        { platform: "Website",   role: "Light",    comment: "Menu & stores" } ],
      themes: { Promotions: 85, Product: 70, Serves: 40, Seasonal: 18, Lifestyle: 12 },
      insight: "Burger King SA ran an aggressive price-led June built around the **Whopper Wednesday** mechanic and challenger-brand jabs at rivals.",
      sentiment: { positive: 58, neutral: 30, negative: 12 }, freq: { Facebook: 16, Instagram: 14, X: 11, TikTok: 8 }, score: 7.1,
      creative: { platformNative: 7, culturalRelevance: 6, visualDistinctiveness: 7, strategicClarity: 7, engagementPotential: 7 },
      exec: "A discount-heavy challenger play — strong on offers and flame-grill craft cues, lighter on cultural and lifestyle content.",
      campaigns: [{ title: "Whopper Wednesday", description: "Weekly price mechanic anchoring the month." }],
      whitespace: "Heavy discounting risks brand equity erosion.", rec: "Avoid a discount war; compete on distinctiveness." }),
    demoCard({ name: "Nando's SA", handle: "@nandossa", color: "#DC0032", parent: "qsr",
      ig: "https://instagram.com/nandossa", fb: "https://facebook.com/NandosSA", x: "https://x.com/NandosSA", tiktok: "@nandos.sa", web: "https://nandos.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Witty topical" },
        { platform: "Instagram", role: "Primary",  comment: "Bold art direction" },
        { platform: "X",         role: "Primary",  comment: "Topical commentary" },
        { platform: "TikTok",    role: "Light",    comment: "Brand humour" },
        { platform: "Website",   role: "Light",    comment: "Menu & PERi-PERi" } ],
      themes: { Promotions: 40, Product: 55, Serves: 30, Seasonal: 20, Lifestyle: 70 },
      insight: "Nando's SA stayed true to its wit-led playbook, using **topical current-affairs** creative and bold art direction to drive earned reach rather than discounting.",
      sentiment: { positive: 80, neutral: 15, negative: 5 }, freq: { Facebook: 14, Instagram: 16, X: 18, TikTok: 7 }, score: 8.7,
      creative: { platformNative: 8, culturalRelevance: 10, visualDistinctiveness: 9, strategicClarity: 9, engagementPotential: 9 },
      exec: "Nando's continued to win on distinctiveness and cultural commentary, generating outsized earned reach without leaning on price.",
      campaigns: [{ title: "Topical wit", description: "Reactive current-affairs creative driving earned media." }],
      whitespace: "Lower posting frequency than QSR peers.", rec: "Distinctiveness beats discounting — the Nando's model is the benchmark.",
      signalMatch: true, signalNote: "Found a **topical** load-shedding ad dated 14 June that drove strong earned reach.", signalLink: "https://x.com/NandosSA" }),
  ],
  alcohol: [
    demoCard({ name: "Castle Lite", handle: "@castlelitesa", color: "#4A7FB5", parent: "hunters",
      ig: "https://instagram.com/castlelitesa", fb: "https://facebook.com/CastleLite", x: "https://x.com/CastleLite", web: "https://castlelite.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Extra-cold lifestyle" },
        { platform: "Instagram", role: "Primary",  comment: "Music & events" },
        { platform: "X",         role: "Light",    comment: "Live event banter" },
        { platform: "Website",   role: "Primary",  comment: "Brand & events" } ],
      themes: { Promotions: 35, Product: 55, Serves: 40, Seasonal: 30, Lifestyle: 80 },
      insight: "Castle Lite reinforced its 'extra cold' equity through aspirational lifestyle content, anchored by the **Castle Lite Unlocked** music platform and a **#ExtraCold** summer push.",
      sentiment: { positive: 74, neutral: 20, negative: 6 }, freq: { Facebook: 16, Instagram: 22, X: 12 }, score: 8.5,
      creative: { platformNative: 9, culturalRelevance: 9, visualDistinctiveness: 8, strategicClarity: 9, engagementPotential: 8 },
      exec: "Premium lifestyle and music-led, Castle Lite defended its leadership through experiential equity rather than promotion.",
      campaigns: [{ title: "Castle Lite Unlocked", description: "Flagship music platform driving cultural relevance." }],
      whitespace: "Light on at-home / serve occasions.", rec: "Hunters can own the relaxed, everyday occasion Castle Lite skips.",
      signalMatch: true, signalNote: "Found a **Castle Lite Unlocked** line-up reveal dated 11 June across Instagram and Facebook.", signalLink: "https://instagram.com/castlelitesa" }),
    demoCard({ name: "Flying Fish", handle: "@flyingfishsa", color: "#16A085", parent: "hunters",
      ig: "https://instagram.com/flyingfishsa", fb: "https://facebook.com/FlyingFishSA", x: "https://x.com/FlyingFishSA", web: "https://flyingfish.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Flavour & fun" },
        { platform: "Instagram", role: "Primary",  comment: "Bold, youthful" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "Website",   role: "Light",    comment: "Product range" } ],
      themes: { Promotions: 55, Product: 75, Serves: 35, Seasonal: 25, Lifestyle: 50 },
      insight: "Flying Fish leaned into flavour-led fun, using the **FIFA World Cup** sponsorship hook and bright creator content to court a younger LDA+ audience.",
      sentiment: { positive: 70, neutral: 22, negative: 8 }, freq: { Facebook: 18, Instagram: 20, X: 0 }, score: 7.8,
      creative: { platformNative: 8, culturalRelevance: 8, visualDistinctiveness: 8, strategicClarity: 7, engagementPotential: 8 },
      exec: "Flavoured-beer fun with a sport hook — youthful and high-energy, though strategy is spread across several messages.",
      campaigns: [{ title: "FIFA World Cup", description: "Football sponsorship hook for the period." }],
      whitespace: "Message focus is diffuse across flavour, sport and music.", rec: "A sharper single-minded hook would lift Flying Fish's effectiveness.",
      signalMatch: true, signalNote: "Found a **FIFA World Cup** flavour-upgrade activation dated 7 June on Instagram.", signalLink: "https://instagram.com/flyingfishsa" }),
    demoCard({ name: "Brutal Fruit", handle: "@brutalfruitza", color: "#E84393", parent: "hunters",
      ig: "https://instagram.com/brutalfruitza", fb: "https://facebook.com/BrutalFruit", x: "https://x.com/BrutalFruit", web: "https://brutalfruit.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Light",    comment: "Elegant lifestyle" },
        { platform: "Instagram", role: "Primary",  comment: "Aspirational, feminine" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "Website",   role: "Light",    comment: "Brand world" } ],
      themes: { Promotions: 30, Product: 50, Serves: 45, Seasonal: 25, Lifestyle: 78 },
      insight: "Brutal Fruit held a premium, feminine lifestyle lane built around the **Ruby Apple** hero and elegant, occasion-led Instagram creative.",
      sentiment: { positive: 76, neutral: 19, negative: 5 }, freq: { Facebook: 10, Instagram: 18, X: 0 }, score: 7.9,
      creative: { platformNative: 8, culturalRelevance: 8, visualDistinctiveness: 9, strategicClarity: 8, engagementPotential: 7 },
      exec: "A focused, premium feminine positioning — strong visual distinctiveness and occasion framing, narrow by design.",
      campaigns: [{ title: "Ruby Apple", description: "Hero SKU anchoring elegant lifestyle creative." }],
      whitespace: "Narrow audience focus; little male or mixed-occasion content.", rec: "Brutal Fruit cedes the broad social occasion Hunters can own." }),
    demoCard({ name: "Savanna", handle: "@savannacider", color: "#F39C12", parent: "hunters",
      ig: "https://instagram.com/savannacider", fb: "https://facebook.com/Savanna", x: "https://x.com/Savanna_Cider", web: "https://savanna.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Comedy & wit" },
        { platform: "Instagram", role: "Primary",  comment: "Humour-led" },
        { platform: "X",         role: "Light",    comment: "Dry one-liners" },
        { platform: "Website",   role: "Light",    comment: "Comedy hub" } ],
      themes: { Promotions: 35, Product: 45, Serves: 30, Seasonal: 20, Lifestyle: 72 },
      insight: "Savanna stayed in its comedy lane, using the **Savanna Comedy** platform and dry one-liners to drive distinctive, highly-shareable content.",
      sentiment: { positive: 78, neutral: 17, negative: 5 }, freq: { Facebook: 15, Instagram: 16, X: 10 }, score: 8.2,
      creative: { platformNative: 8, culturalRelevance: 9, visualDistinctiveness: 9, strategicClarity: 8, engagementPotential: 9 },
      exec: "Comedy-led distinctiveness — Savanna's wit platform continues to deliver outsized share of voice for spend.",
      campaigns: [{ title: "Savanna Comedy", description: "Owned comedy platform driving earned reach." }],
      whitespace: "Humour can crowd out product/occasion cues.", rec: "Hunters can balance wit with clearer occasion framing.",
      signalMatch: true, signalNote: "Found a **Savanna Comedy** special teaser dated 18 June across Facebook and Instagram.", signalLink: "https://facebook.com/Savanna" }),
  ],
  retail: [
    demoCard({ name: "Takealot", handle: "@takealot", color: "#0A9EDC", parent: "retail",
      ig: "https://instagram.com/takealot", fb: "https://facebook.com/takealot", x: "https://x.com/takealot", tiktok: "@takealot", web: "https://takealot.com",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Deals & delivery" },
        { platform: "Instagram", role: "Primary",  comment: "Product discovery" },
        { platform: "X",         role: "Light",    comment: "Customer service" },
        { platform: "TikTok",    role: "Light",    comment: "Trend hauls" },
        { platform: "Website",   role: "Primary",  comment: "Marketplace" } ],
      themes: { Promotions: 82, Product: 70, Serves: 18, Seasonal: 40, Lifestyle: 25 },
      insight: "Takealot ran always-on deal culture in June, with **Blue Dot Sale** teasers and rapid-delivery messaging dominating the feed.",
      sentiment: { positive: 60, neutral: 28, negative: 12 }, freq: { Facebook: 24, Instagram: 22, X: 16, TikTok: 10 }, score: 8.0,
      creative: { platformNative: 8, culturalRelevance: 7, visualDistinctiveness: 7, strategicClarity: 8, engagementPotential: 8 },
      exec: "Marketplace breadth and price are the story — high-volume deal content optimised for conversion over brand-building.",
      campaigns: [{ title: "Blue Dot Sale", description: "Flagship discount event teased through the month." }],
      whitespace: "Little emotional / brand storytelling beyond price.", rec: "A brand can differentiate on trust and curation where Takealot competes purely on deals.",
      signalMatch: true, signalNote: "Found a **Blue Dot Sale** pre-launch teaser dated 12 June across Instagram and Facebook.", signalLink: "https://instagram.com/takealot" }),
    demoCard({ name: "Woolworths SA", handle: "@woolworths_sa", color: "#4A7C2F", parent: "retail",
      ig: "https://instagram.com/woolworths_sa", fb: "https://facebook.com/WoolworthsSA", x: "https://x.com/WOOLWORTHS_SA", tiktok: "@woolworths_sa", web: "https://woolworths.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Food & fashion" },
        { platform: "Instagram", role: "Primary",  comment: "Premium lifestyle" },
        { platform: "X",         role: "Light",    comment: "Service & news" },
        { platform: "TikTok",    role: "Light",    comment: "Food inspiration" },
        { platform: "Website",   role: "Primary",  comment: "Online & Dash" } ],
      themes: { Promotions: 45, Product: 65, Serves: 35, Seasonal: 40, Lifestyle: 75 },
      insight: "Woolworths held a premium lifestyle lane, with **The Woolies Way** quality storytelling and seasonal food content leading June.",
      sentiment: { positive: 72, neutral: 21, negative: 7 }, freq: { Facebook: 18, Instagram: 24, X: 10, TikTok: 9 }, score: 8.5,
      creative: { platformNative: 8, culturalRelevance: 8, visualDistinctiveness: 9, strategicClarity: 9, engagementPotential: 8 },
      exec: "Premium, quality-led and consistent — Woolworths converts brand equity into loyalty rather than chasing discounts.",
      campaigns: [{ title: "The Woolies Way", description: "Quality and provenance storytelling across food and fashion." }],
      whitespace: "Premium positioning leaves value-seekers to rivals.", rec: "Quality storytelling is the benchmark to study here." }),
    demoCard({ name: "Checkers", handle: "@checkerssa", color: "#E2231A", parent: "retail",
      ig: "https://instagram.com/checkerssa", fb: "https://facebook.com/checkers", x: "https://x.com/checkerssa", tiktok: "@checkers_sa", web: "https://checkers.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Sixty60 & deals" },
        { platform: "Instagram", role: "Primary",  comment: "Convenience-led" },
        { platform: "X",         role: "Light",    comment: "Service" },
        { platform: "TikTok",    role: "Primary",  comment: "Sixty60 creators" },
        { platform: "Website",   role: "Primary",  comment: "Sixty60 app" } ],
      themes: { Promotions: 75, Product: 55, Serves: 30, Seasonal: 35, Lifestyle: 40 },
      insight: "Checkers rode its **Sixty60** delivery momentum hard, pairing speed messaging with influencer hauls to own the convenience narrative.",
      sentiment: { positive: 70, neutral: 22, negative: 8 }, freq: { Facebook: 20, Instagram: 20, X: 12, TikTok: 18 }, score: 8.3,
      creative: { platformNative: 9, culturalRelevance: 8, visualDistinctiveness: 7, strategicClarity: 8, engagementPotential: 9 },
      exec: "Sixty60 is the wedge — Checkers turned a delivery app into a culturally-relevant convenience brand.",
      campaigns: [{ title: "Sixty60", description: "60-minute delivery platform driving the brand's momentum." }],
      whitespace: "Brand leans heavily on one product (Sixty60).", rec: "Watch Sixty60's creator playbook — it's the standout convenience model.",
      signalMatch: true, signalNote: "Found a **Sixty60** 'faster than ever' creator push dated 8 June on TikTok.", signalLink: "https://instagram.com/checkerssa" }),
    demoCard({ name: "Mr Price", handle: "@mrpricefashion", color: "#E4002B", parent: "retail",
      ig: "https://instagram.com/mrpricefashion", fb: "https://facebook.com/MRPFashion", x: "https://x.com/MRP_Fashion", tiktok: "@mrpfashion", web: "https://mrp.com",
      snapshot: [
        { platform: "Facebook",  role: "Light",    comment: "Fashion drops" },
        { platform: "Instagram", role: "Primary",  comment: "Youth fashion" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "TikTok",    role: "Primary",  comment: "Style creators" },
        { platform: "Website",   role: "Primary",  comment: "Shop online" } ],
      themes: { Promotions: 60, Product: 70, Serves: 20, Seasonal: 45, Lifestyle: 55 },
      insight: "Mr Price targeted Gen-Z value fashion, using **#MRPxStyle** creator drops and TikTok-first content to drive affordable trend appeal.",
      sentiment: { positive: 66, neutral: 26, negative: 8 }, freq: { Facebook: 12, Instagram: 22, X: 0, TikTok: 24 }, score: 7.7,
      creative: { platformNative: 9, culturalRelevance: 8, visualDistinctiveness: 7, strategicClarity: 7, engagementPotential: 8 },
      exec: "TikTok-native and youth-led — Mr Price competes on affordable trend speed and creator volume.",
      campaigns: [{ title: "#MRPxStyle", description: "Creator-led fashion drops aimed at Gen-Z." }],
      whitespace: "X/Twitter dormant; opportunity for service voice.", rec: "Mr Price's TikTok-first model is worth benchmarking for youth reach." }),
  ],
  telecoms: [
    demoCard({ name: "Vodacom", handle: "@vodacom", color: "#E60000", parent: "telecoms",
      ig: "https://instagram.com/vodacom", fb: "https://facebook.com/Vodacom", x: "https://x.com/Vodacom", tiktok: "@vodacom", web: "https://vodacom.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Data deals & care" },
        { platform: "Instagram", role: "Primary",  comment: "Lifestyle & sport" },
        { platform: "X",         role: "Primary",  comment: "Live service" },
        { platform: "TikTok",    role: "Light",    comment: "Youth trends" },
        { platform: "Website",   role: "Primary",  comment: "Plans & app" } ],
      themes: { Promotions: 70, Product: 60, Serves: 45, Seasonal: 25, Lifestyle: 50 },
      insight: "Vodacom led on scale and sport, anchoring June around **VodaPay** super-app pushes and its national sponsorship portfolio.",
      sentiment: { positive: 58, neutral: 27, negative: 15 }, freq: { Facebook: 24, Instagram: 22, X: 26, TikTok: 12 }, score: 7.9,
      creative: { platformNative: 8, culturalRelevance: 8, visualDistinctiveness: 7, strategicClarity: 8, engagementPotential: 7 },
      exec: "Market leader playing the breadth game — data value, super-app and sport sponsorship across a high-volume feed.",
      campaigns: [{ title: "VodaPay", description: "Super-app adoption drive." }],
      whitespace: "High service-complaint volume on X dents sentiment.", rec: "Service responsiveness is a soft spot to exploit.",
      signalMatch: true, signalNote: "Found a **VodaPay** rewards push dated 10 June across Facebook and Instagram.", signalLink: "https://instagram.com/vodacom" }),
    demoCard({ name: "MTN SA", handle: "@mtnza", color: "#FFCB05", parent: "telecoms",
      ig: "https://instagram.com/mtnza", fb: "https://facebook.com/mtn.co.za", x: "https://x.com/MTNza", tiktok: "@mtnza", web: "https://mtn.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Deals & football" },
        { platform: "Instagram", role: "Primary",  comment: "Bold yellow brand" },
        { platform: "X",         role: "Primary",  comment: "Service & news" },
        { platform: "TikTok",    role: "Primary",  comment: "Creator content" },
        { platform: "Website",   role: "Primary",  comment: "Plans & MoMo" } ],
      themes: { Promotions: 68, Product: 58, Serves: 40, Seasonal: 30, Lifestyle: 55 },
      insight: "MTN pushed its **MoMo** financial play and football heritage, with bold yellow creative and a strong TikTok creator presence.",
      sentiment: { positive: 60, neutral: 28, negative: 12 }, freq: { Facebook: 22, Instagram: 24, X: 22, TikTok: 18 }, score: 8.1,
      creative: { platformNative: 9, culturalRelevance: 8, visualDistinctiveness: 9, strategicClarity: 8, engagementPotential: 8 },
      exec: "Distinctive brand assets plus a fintech (MoMo) and football narrative — MTN is the most creatively confident of the networks.",
      campaigns: [{ title: "MoMo", description: "Mobile money adoption push." }],
      whitespace: "Fintech story still feels separate from core telco.", rec: "MTN's distinctive yellow system is the brand-asset benchmark." }),
    demoCard({ name: "Telkom", handle: "@telkomza", color: "#00A9CE", parent: "telecoms",
      ig: "https://instagram.com/telkomza", fb: "https://facebook.com/Telkom", x: "https://x.com/TelkomZA", tiktok: "@telkomza", web: "https://telkom.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Data value" },
        { platform: "Instagram", role: "Light",    comment: "Product-led" },
        { platform: "X",         role: "Primary",  comment: "Service-heavy" },
        { platform: "TikTok",    role: "Inactive", comment: "" },
        { platform: "Website",   role: "Primary",  comment: "Deals & fibre" } ],
      themes: { Promotions: 78, Product: 62, Serves: 50, Seasonal: 20, Lifestyle: 18 },
      insight: "Telkom competed almost entirely on **data value**, with price-led creative and a heavy customer-service load on X.",
      sentiment: { positive: 48, neutral: 30, negative: 22 }, freq: { Facebook: 18, Instagram: 12, X: 24, TikTok: 0 }, score: 6.8,
      creative: { platformNative: 6, culturalRelevance: 5, visualDistinctiveness: 6, strategicClarity: 7, engagementPotential: 6 },
      exec: "Value-challenger with a thin brand layer — strong on price, weak on culture and distinctiveness.",
      campaigns: [{ title: "Data value", description: "Price-led data bundle messaging." }],
      whitespace: "No TikTok presence; weak brand-building.", rec: "Telkom's culture gap is wide open for a more distinctive challenger." }),
    demoCard({ name: "Rain", handle: "@rain.networks", color: "#6C2BD9", parent: "telecoms",
      ig: "https://instagram.com/rain.networks", fb: "https://facebook.com/rain.networks", x: "https://x.com/rainmobiledata", tiktok: "@rain.networks", web: "https://rain.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Light",    comment: "Data-only" },
        { platform: "Instagram", role: "Primary",  comment: "Clean, minimal" },
        { platform: "X",         role: "Primary",  comment: "Disruptor voice" },
        { platform: "TikTok",    role: "Light",    comment: "Explainers" },
        { platform: "Website",   role: "Primary",  comment: "Sign-up funnel" } ],
      themes: { Promotions: 55, Product: 72, Serves: 30, Seasonal: 15, Lifestyle: 35 },
      insight: "Rain played the data-only disruptor, with minimalist creative and **unlimited 5G** messaging aimed at cutting out the legacy networks.",
      sentiment: { positive: 64, neutral: 26, negative: 10 }, freq: { Facebook: 10, Instagram: 16, X: 18, TikTok: 8 }, score: 7.4,
      creative: { platformNative: 7, culturalRelevance: 7, visualDistinctiveness: 8, strategicClarity: 9, engagementPotential: 7 },
      exec: "Single-minded disruptor — clean design and a sharp 5G value proposition, narrow but focused.",
      campaigns: [{ title: "Unlimited 5G", description: "Data-only disruption play vs incumbents." }],
      whitespace: "Narrow product focus limits reach.", rec: "Rain's clarity of proposition is a lesson in single-minded messaging." }),
  ],
  beauty: [
    demoCard({ name: "MAC Cosmetics", handle: "@maccosmetics", color: "#B11226", parent: "beauty",
      ig: "https://instagram.com/maccosmetics", fb: "https://facebook.com/maccosmetics", x: "https://x.com/MACcosmetics", tiktok: "@maccosmetics", web: "https://maccosmetics.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Light",    comment: "Product launches" },
        { platform: "Instagram", role: "Primary",  comment: "Artistry-led" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "TikTok",    role: "Primary",  comment: "MUA tutorials" },
        { platform: "Website",   role: "Primary",  comment: "Shop & shades" } ],
      themes: { Promotions: 40, Product: 80, Serves: 25, Seasonal: 30, Lifestyle: 60 },
      insight: "MAC stayed artistry-first, with **#MACArtistChallenge** creator content and bold shade-led product storytelling driving June.",
      sentiment: { positive: 74, neutral: 20, negative: 6 }, freq: { Facebook: 10, Instagram: 24, X: 0, TikTok: 22 }, score: 8.4,
      creative: { platformNative: 9, culturalRelevance: 9, visualDistinctiveness: 9, strategicClarity: 8, engagementPotential: 9 },
      exec: "Pro-artistry credibility plus creator volume — MAC converts makeup-artist authority into aspirational reach.",
      campaigns: [{ title: "#MACArtistChallenge", description: "Creator artistry series showcasing shade range." }],
      whitespace: "Premium price point leaves value-beauty open.", rec: "MAC's artistry-credibility model is the aspirational benchmark.",
      signalMatch: true, signalNote: "Found a **#MACArtistChallenge** creator series dated 13 June across Instagram and TikTok.", signalLink: "https://instagram.com/maccosmetics" }),
    demoCard({ name: "NYX SA", handle: "@nyxcosmetics_sa", color: "#D4498F", parent: "beauty",
      ig: "https://instagram.com/nyxcosmetics_sa", fb: "https://facebook.com/nyxcosmeticssa", x: "https://x.com/NYXCosmeticsSA", tiktok: "@nyxcosmetics", web: "https://nyxcosmetics.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Light",    comment: "Promos" },
        { platform: "Instagram", role: "Primary",  comment: "Trend-led colour" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "TikTok",    role: "Primary",  comment: "Viral products" },
        { platform: "Website",   role: "Primary",  comment: "Shop online" } ],
      themes: { Promotions: 60, Product: 75, Serves: 20, Seasonal: 30, Lifestyle: 50 },
      insight: "NYX chased TikTok virality, with the **Fat Oil Lip Drip** hero product and creator-driven dupes leading affordable colour cosmetics.",
      sentiment: { positive: 70, neutral: 23, negative: 7 }, freq: { Facebook: 9, Instagram: 20, X: 0, TikTok: 28 }, score: 8.0,
      creative: { platformNative: 9, culturalRelevance: 9, visualDistinctiveness: 7, strategicClarity: 8, engagementPotential: 9 },
      exec: "TikTok-native and product-hero-led — NYX wins on affordable virality and creator dupes.",
      campaigns: [{ title: "Fat Oil Lip Drip", description: "Viral hero product anchoring TikTok content." }],
      whitespace: "Brand world is thin beyond product virality.", rec: "NYX shows how a single hero SKU can drive a whole TikTok strategy." }),
    demoCard({ name: "Estée Lauder", handle: "@esteelauder", color: "#1B3A5B", parent: "beauty",
      ig: "https://instagram.com/esteelauder", fb: "https://facebook.com/esteelauder", x: "https://x.com/EsteeLauder", tiktok: "@esteelauder", web: "https://esteelauder.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Light",    comment: "Skincare-beauty" },
        { platform: "Instagram", role: "Primary",  comment: "Luxury editorial" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "TikTok",    role: "Light",    comment: "Serum science" },
        { platform: "Website",   role: "Primary",  comment: "Shop & gifting" } ],
      themes: { Promotions: 35, Product: 78, Serves: 25, Seasonal: 35, Lifestyle: 65 },
      insight: "Estée Lauder held a luxury editorial lane, with **Advanced Night Repair** serum science and gifting-led creative anchoring the period.",
      sentiment: { positive: 72, neutral: 22, negative: 6 }, freq: { Facebook: 8, Instagram: 18, X: 0, TikTok: 10 }, score: 7.8,
      creative: { platformNative: 7, culturalRelevance: 7, visualDistinctiveness: 9, strategicClarity: 8, engagementPotential: 7 },
      exec: "Prestige and product science — polished, premium, less culturally-native than the colour brands.",
      campaigns: [{ title: "Advanced Night Repair", description: "Hero serum science storytelling." }],
      whitespace: "Limited cultural / creator relevance.", rec: "Prestige craft is strong; cultural relevance is contestable." }),
    demoCard({ name: "Maybelline SA", handle: "@maybelline", color: "#0033A0", parent: "beauty",
      ig: "https://instagram.com/maybelline", fb: "https://facebook.com/maybelline", x: "https://x.com/Maybelline", tiktok: "@maybelline", web: "https://maybelline.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Mass-market promos" },
        { platform: "Instagram", role: "Primary",  comment: "Everyday glam" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "TikTok",    role: "Primary",  comment: "Sky-High virals" },
        { platform: "Website",   role: "Light",    comment: "Find a shade" } ],
      themes: { Promotions: 58, Product: 72, Serves: 22, Seasonal: 28, Lifestyle: 48 },
      insight: "Maybelline drove mass-market accessibility, with the **Sky High Mascara** hero and everyday-glam creator content sustaining reach.",
      sentiment: { positive: 68, neutral: 24, negative: 8 }, freq: { Facebook: 16, Instagram: 20, X: 0, TikTok: 22 }, score: 7.9,
      creative: { platformNative: 8, culturalRelevance: 8, visualDistinctiveness: 7, strategicClarity: 8, engagementPotential: 8 },
      exec: "Accessible everyday glam at scale — strong hero products and broad creator reach.",
      campaigns: [{ title: "Sky High Mascara", description: "Viral hero product sustaining mass reach." }],
      whitespace: "Crowded everyday-glam space; little distinctiveness.", rec: "Maybelline shows hero-product consistency, but distinctiveness is winnable." }),
  ],
  skincare: [
    demoCard({ name: "Nivea SA", handle: "@niveasa", color: "#003DA5", parent: "skincare",
      ig: "https://instagram.com/niveasa", fb: "https://facebook.com/NiveaSA", x: "https://x.com/NiveaSA", tiktok: "@niveasa", web: "https://nivea.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Family skincare" },
        { platform: "Instagram", role: "Primary",  comment: "Tips & tutorials" },
        { platform: "X",         role: "Light",    comment: "Customer care" },
        { platform: "TikTok",    role: "Light",    comment: "Routine content" },
        { platform: "Website",   role: "Primary",  comment: "Product range" } ],
      themes: { Promotions: 50, Product: 78, Serves: 25, Seasonal: 35, Lifestyle: 45 },
      insight: "Nivea anchored June on the **Winter Skin SOS** seasonal push, pairing dermatologist creators with its Q10 range relaunch.",
      sentiment: { positive: 76, neutral: 18, negative: 6 }, freq: { Facebook: 18, Instagram: 20, X: 9, TikTok: 12 }, score: 8.1,
      creative: { platformNative: 8, culturalRelevance: 7, visualDistinctiveness: 8, strategicClarity: 9, engagementPotential: 8 },
      exec: "Trusted mass skincare — seasonal relevance plus dermatologist credibility drive broad reach.",
      campaigns: [{ title: "Winter Skin SOS", description: "Seasonal dry-skin campaign with creator dermatologists." }],
      whitespace: "Mass-trust positioning leaves premium derma open.", rec: "Nivea's seasonal-relevance playbook is the mass benchmark.",
      signalMatch: true, signalNote: "Found a **Winter Skin SOS** launch post dated 4 June promoting the moisturiser range.", signalLink: "https://instagram.com/niveasa" }),
    demoCard({ name: "Bio-Oil", handle: "@bio_oil", color: "#E8B64C", parent: "skincare",
      ig: "https://instagram.com/bio_oil", fb: "https://facebook.com/BioOil", x: "https://x.com/BioOil", tiktok: "@biooil", web: "https://bio-oil.com",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Scar & skin claims" },
        { platform: "Instagram", role: "Primary",  comment: "Real-skin stories" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "TikTok",    role: "Light",    comment: "Before/after" },
        { platform: "Website",   role: "Light",    comment: "Skin concerns" } ],
      themes: { Promotions: 40, Product: 80, Serves: 30, Seasonal: 20, Lifestyle: 50 },
      insight: "Bio-Oil leaned into efficacy proof, with **real-skin transformation** stories and scar/stretch-mark claims dominating its single-hero feed.",
      sentiment: { positive: 78, neutral: 17, negative: 5 }, freq: { Facebook: 14, Instagram: 16, X: 0, TikTok: 10 }, score: 7.7,
      creative: { platformNative: 7, culturalRelevance: 7, visualDistinctiveness: 8, strategicClarity: 9, engagementPotential: 7 },
      exec: "Single-hero focus with strong efficacy proof — narrow range, very clear claim.",
      campaigns: [{ title: "Real-skin stories", description: "User transformation content proving efficacy." }],
      whitespace: "One-product brand; limited routine play.", rec: "Bio-Oil's proof-led storytelling is worth studying for credibility." }),
    demoCard({ name: "The Ordinary", handle: "@theordinary", color: "#6B7280", parent: "skincare",
      ig: "https://instagram.com/theordinary", fb: "https://facebook.com/theordinary", x: "https://x.com/theordinary", tiktok: "@theordinary", web: "https://theordinary.com",
      snapshot: [
        { platform: "Facebook",  role: "Light",    comment: "Ingredient-led" },
        { platform: "Instagram", role: "Primary",  comment: "Clinical minimal" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "TikTok",    role: "Primary",  comment: "Ingredient education" },
        { platform: "Website",   role: "Primary",  comment: "Regimen builder" } ],
      themes: { Promotions: 30, Product: 82, Serves: 25, Seasonal: 15, Lifestyle: 40 },
      insight: "The Ordinary won on transparency, with **ingredient-education** content and its clinical-minimal aesthetic driving a science-led following.",
      sentiment: { positive: 75, neutral: 20, negative: 5 }, freq: { Facebook: 8, Instagram: 18, X: 0, TikTok: 20 }, score: 8.3,
      creative: { platformNative: 9, culturalRelevance: 8, visualDistinctiveness: 9, strategicClarity: 9, engagementPotential: 8 },
      exec: "Transparency and affordability as brand — ingredient education builds trust and TikTok reach.",
      campaigns: [{ title: "Ingredient education", description: "Explainer content demystifying actives." }],
      whitespace: "Clinical tone can feel cold / impersonal.", rec: "The Ordinary's transparency model is the trust-building benchmark." }),
    demoCard({ name: "Cetaphil SA", handle: "@cetaphil_sa", color: "#0093D0", parent: "skincare",
      ig: "https://instagram.com/cetaphil_sa", fb: "https://facebook.com/CetaphilSA", x: "https://x.com/Cetaphil", tiktok: "@cetaphil", web: "https://cetaphil.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Derma-recommended" },
        { platform: "Instagram", role: "Primary",  comment: "Sensitive-skin" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "TikTok",    role: "Light",    comment: "Gentle routines" },
        { platform: "Website",   role: "Light",    comment: "Skin advice" } ],
      themes: { Promotions: 38, Product: 76, Serves: 30, Seasonal: 25, Lifestyle: 42 },
      insight: "Cetaphil owned the gentle, derma-recommended space, with **#CetaphilGentle** content and sensitive-skin authority leading June.",
      sentiment: { positive: 74, neutral: 21, negative: 5 }, freq: { Facebook: 14, Instagram: 16, X: 0, TikTok: 11 }, score: 7.6,
      creative: { platformNative: 7, culturalRelevance: 7, visualDistinctiveness: 7, strategicClarity: 8, engagementPotential: 7 },
      exec: "Derma-trust positioning — gentle, sensitive-skin authority with steady, reassuring content.",
      campaigns: [{ title: "#CetaphilGentle", description: "Sensitive-skin authority content." }],
      whitespace: "Functional tone; limited lifestyle appeal.", rec: "Cetaphil's derma-trust angle is a credibility benchmark." }),
  ],
  haircare: [
    demoCard({ name: "Cantu SA", handle: "@cantubeauty", color: "#C97B3C", parent: "haircare",
      ig: "https://instagram.com/cantubeauty", fb: "https://facebook.com/cantubeauty", x: "https://x.com/cantubeauty", tiktok: "@cantubeauty", web: "https://cantubeauty.com",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Curl care" },
        { platform: "Instagram", role: "Primary",  comment: "Natural-hair pride" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "TikTok",    role: "Primary",  comment: "Wash-day routines" },
        { platform: "Website",   role: "Light",    comment: "Product finder" } ],
      themes: { Promotions: 45, Product: 75, Serves: 30, Seasonal: 20, Lifestyle: 65 },
      insight: "Cantu celebrated natural-hair culture, with **#CantuCurls** wash-day creator routines and texture-positive content leading June.",
      sentiment: { positive: 78, neutral: 17, negative: 5 }, freq: { Facebook: 14, Instagram: 20, X: 0, TikTok: 24 }, score: 8.2,
      creative: { platformNative: 9, culturalRelevance: 10, visualDistinctiveness: 8, strategicClarity: 8, engagementPotential: 9 },
      exec: "Community-led and culturally rooted — Cantu owns natural-hair pride with authentic creator content.",
      campaigns: [{ title: "#CantuCurls", description: "Wash-day routine creator series." }],
      whitespace: "Heavy curl focus; little straight/relaxed content.", rec: "Cantu's cultural authenticity is the haircare benchmark.",
      signalMatch: true, signalNote: "Found a **#CantuCurls** wash-day creator series dated 6 June on TikTok and Instagram.", signalLink: "https://instagram.com/cantubeauty" }),
    demoCard({ name: "Dark and Lovely", handle: "@darkandlovely", color: "#7D3C98", parent: "haircare",
      ig: "https://instagram.com/darkandlovelysa", fb: "https://facebook.com/DarkandLovelySA", x: "https://x.com/darkandlovely", tiktok: "@darkandlovely", web: "https://darkandlovely.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Colour & care" },
        { platform: "Instagram", role: "Primary",  comment: "Bold transformations" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "TikTok",    role: "Light",    comment: "Colour reveals" },
        { platform: "Website",   role: "Light",    comment: "Shade range" } ],
      themes: { Promotions: 55, Product: 72, Serves: 25, Seasonal: 25, Lifestyle: 55 },
      insight: "Dark and Lovely drove bold self-expression, with **colour-transformation** reveals and heritage-brand trust anchoring its feed.",
      sentiment: { positive: 70, neutral: 23, negative: 7 }, freq: { Facebook: 16, Instagram: 18, X: 0, TikTok: 12 }, score: 7.5,
      creative: { platformNative: 7, culturalRelevance: 8, visualDistinctiveness: 8, strategicClarity: 7, engagementPotential: 7 },
      exec: "Heritage trust plus bold colour — strong transformation content, lighter on creator-native formats.",
      campaigns: [{ title: "Colour transformations", description: "Before/after colour reveal content." }],
      whitespace: "Less creator-native than Cantu.", rec: "Heritage trust is an asset; creator formats are the gap." }),
    demoCard({ name: "TRESemmé SA", handle: "@tresemmesa", color: "#444444", parent: "haircare",
      ig: "https://instagram.com/tresemmesa", fb: "https://facebook.com/TRESemmeSA", x: "https://x.com/TRESemme", tiktok: "@tresemme", web: "https://tresemme.co.za",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Salon-at-home" },
        { platform: "Instagram", role: "Primary",  comment: "Pro styling" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "TikTok",    role: "Light",    comment: "Style hacks" },
        { platform: "Website",   role: "Light",    comment: "Routines" } ],
      themes: { Promotions: 50, Product: 70, Serves: 28, Seasonal: 22, Lifestyle: 52 },
      insight: "TRESemmé pushed its **salon-professional** positioning, with styling-routine content and pro-quality cues leading the period.",
      sentiment: { positive: 66, neutral: 26, negative: 8 }, freq: { Facebook: 14, Instagram: 16, X: 0, TikTok: 10 }, score: 7.3,
      creative: { platformNative: 7, culturalRelevance: 6, visualDistinctiveness: 7, strategicClarity: 8, engagementPotential: 7 },
      exec: "Salon-pro positioning at mass price — consistent styling content, limited cultural specificity.",
      campaigns: [{ title: "Salon professional", description: "Pro-quality styling-at-home messaging." }],
      whitespace: "Generic vs locally-rooted rivals.", rec: "TRESemmé's pro positioning is sound but culturally generic." }),
    demoCard({ name: "SheaMoisture", handle: "@sheamoisture", color: "#2E7D32", parent: "haircare",
      ig: "https://instagram.com/sheamoisture", fb: "https://facebook.com/SheaMoisture", x: "https://x.com/SheaMoisture", tiktok: "@sheamoisture", web: "https://sheamoisture.com",
      snapshot: [
        { platform: "Facebook",  role: "Light",    comment: "Natural ingredients" },
        { platform: "Instagram", role: "Primary",  comment: "Clean & community" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "TikTok",    role: "Primary",  comment: "Curl routines" },
        { platform: "Website",   role: "Light",    comment: "Hair quiz" } ],
      themes: { Promotions: 40, Product: 72, Serves: 30, Seasonal: 18, Lifestyle: 68 },
      insight: "SheaMoisture led with purpose, pairing **clean-ingredient** storytelling and community values with curl-routine creator content.",
      sentiment: { positive: 76, neutral: 19, negative: 5 }, freq: { Facebook: 10, Instagram: 18, X: 0, TikTok: 20 }, score: 7.8,
      creative: { platformNative: 8, culturalRelevance: 9, visualDistinctiveness: 8, strategicClarity: 8, engagementPotential: 8 },
      exec: "Purpose and clean-ingredient led — community values plus curl expertise build loyal advocacy.",
      campaigns: [{ title: "Clean ingredients", description: "Natural-ingredient and community-values storytelling." }],
      whitespace: "Premium-natural price limits mass reach.", rec: "SheaMoisture's purpose-led model is the values benchmark." }),
  ],
};

/* US / UK demo sets (key demo verticals). Other categories fall back to SA. */
const DEMO_DATA_US = {
  qsr: [
    demoCard({ name: "McDonald's", handle: "@mcdonalds", color: "#FFC72C", parent: "qsr",
      ig: "https://instagram.com/mcdonalds", fb: "https://facebook.com/McDonalds", x: "https://x.com/McDonalds", tiktok: "@mcdonalds", web: "https://mcdonalds.com",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Cultural moments" },
        { platform: "Instagram", role: "Primary",  comment: "Hero product, drops" },
        { platform: "X",         role: "Primary",  comment: "Reactive banter" },
        { platform: "TikTok",    role: "Primary",  comment: "Trend-native" },
        { platform: "Website",   role: "Primary",  comment: "App & rewards" } ],
      themes: { Promotions: 70, Product: 65, Serves: 25, Seasonal: 40, Lifestyle: 50 },
      insight: "McDonald's anchored June on the **FIFA World Cup 26** tie-in and app-led value, leaning on collectible cups and limited drops to drive cultural reach.",
      sentiment: { positive: 64, neutral: 26, negative: 10 }, freq: { Facebook: 20, Instagram: 25, X: 30, TikTok: 22 }, score: 8.3,
      creative: { platformNative: 9, culturalRelevance: 9, visualDistinctiveness: 8, strategicClarity: 8, engagementPotential: 9 },
      exec: "Scale plus culture — McDonald's converts mass reach and timely tie-ins into the category's loudest share of voice.",
      campaigns: [{ title: "FIFA World Cup 26", description: "Global sponsorship tie-in with collectibles and LTOs." }],
      whitespace: "Premium / quality cues are light vs the value noise.", rec: "Challengers can own craft where McDonald's stays mass-value.",
      signalMatch: true, signalNote: "Found a **FIFA World Cup 26** collectible-cup launch dated 9 June across Instagram and TikTok.", signalLink: "https://instagram.com/mcdonalds" }),
    demoCard({ name: "Wendy's", handle: "@wendys", color: "#E2231A", parent: "qsr",
      ig: "https://instagram.com/wendys", fb: "https://facebook.com/wendys", x: "https://x.com/wendys", tiktok: "@wendys", web: "https://wendys.com",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Humorous, topical" },
        { platform: "Instagram", role: "Primary",  comment: "Product & culture" },
        { platform: "X",         role: "Primary",  comment: "Famous roasts" },
        { platform: "TikTok",    role: "Primary",  comment: "Viral humour" },
        { platform: "Website",   role: "Light",    comment: "Offers & news" } ],
      themes: { Promotions: 60, Product: 60, Serves: 25, Seasonal: 30, Lifestyle: 45 },
      insight: "Wendy's leaned on its signature wit, with the **Minions & Monsters Meal** collab and the **Banana Frosty Swirl** driving outsized TikTok and X engagement.",
      sentiment: { positive: 70, neutral: 20, negative: 10 }, freq: { Facebook: 18, Instagram: 22, X: 28, TikTok: 24 }, score: 8.5,
      creative: { platformNative: 9, culturalRelevance: 9, visualDistinctiveness: 9, strategicClarity: 8, engagementPotential: 9 },
      exec: "Distinctive brand voice — Wendy's punches above its spend through humour and timely collabs.",
      campaigns: [{ title: "Minions & Monsters Meal", description: "Film collab meal with collectibles." }, { title: "Banana Frosty Swirl", description: "Seasonal LTO dessert drop." }],
      whitespace: "Humour can crowd out clear value messaging.", rec: "Wendy's voice is the engagement benchmark to study.",
      signalMatch: true, signalNote: "Found a **Banana Frosty Swirl** launch dated 5 June on Instagram and TikTok.", signalLink: "https://instagram.com/wendys" }),
    demoCard({ name: "Chick-fil-A", handle: "@chickfila", color: "#E51636", parent: "qsr",
      ig: "https://instagram.com/chickfila", fb: "https://facebook.com/ChickfilA", x: "https://x.com/ChickfilA", tiktok: "@chickfila", web: "https://chick-fil-a.com",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Community & service" },
        { platform: "Instagram", role: "Primary",  comment: "Warm, food-led" },
        { platform: "X",         role: "Light",    comment: "Service" },
        { platform: "TikTok",    role: "Inactive", comment: "No TikTok presence" },
        { platform: "Website",   role: "Primary",  comment: "App & rewards" } ],
      themes: { Promotions: 45, Product: 70, Serves: 35, Seasonal: 30, Lifestyle: 55 },
      insight: "Chick-fil-A held a warm, community-led lane around the **Summer Reading** programme and app rewards, prioritising brand affinity over trend-chasing.",
      sentiment: { positive: 78, neutral: 17, negative: 5 }, freq: { Facebook: 16, Instagram: 18, X: 8, TikTok: 0 }, score: 8.0,
      creative: { platformNative: 7, culturalRelevance: 8, visualDistinctiveness: 8, strategicClarity: 9, engagementPotential: 7 },
      exec: "Affinity-led — high trust and loyalty, deliberately off the trend treadmill (and off TikTok).",
      campaigns: [{ title: "Summer Reading", description: "Family programme reinforcing brand values." }],
      whitespace: "No TikTok presence — a gap rivals exploit for youth reach.", rec: "TikTok is open territory against Chick-fil-A." }),
    demoCard({ name: "Taco Bell", handle: "@tacobell", color: "#702082", parent: "qsr",
      ig: "https://instagram.com/tacobell", fb: "https://facebook.com/tacobell", x: "https://x.com/tacobell", tiktok: "@tacobell", web: "https://tacobell.com",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Fan culture" },
        { platform: "Instagram", role: "Primary",  comment: "Bold, playful" },
        { platform: "X",         role: "Primary",  comment: "Fan engagement" },
        { platform: "TikTok",    role: "Primary",  comment: "Menu-hack trends" },
        { platform: "Website",   role: "Primary",  comment: "Rewards & app" } ],
      themes: { Promotions: 65, Product: 70, Serves: 30, Seasonal: 35, Lifestyle: 50 },
      insight: "Taco Bell drove fandom through the **Live Más Live** events and menu-hack culture, with value bundles and app rewards anchoring conversion.",
      sentiment: { positive: 68, neutral: 22, negative: 10 }, freq: { Facebook: 16, Instagram: 20, X: 18, TikTok: 22 }, score: 7.9,
      creative: { platformNative: 8, culturalRelevance: 8, visualDistinctiveness: 8, strategicClarity: 7, engagementPotential: 8 },
      exec: "Fandom-led innovation — Taco Bell turns menu experimentation into participatory culture.",
      campaigns: [{ title: "Live Más Live", description: "Fan-event platform driving menu buzz." }],
      whitespace: "Message spread across many LTOs dilutes focus.", rec: "A sharper hero focus would lift Taco Bell's clarity." }),
  ],
  alcohol: [
    demoCard({ name: "White Claw", handle: "@whiteclaw", color: "#9CC3D5", parent: "hunters",
      ig: "https://instagram.com/whiteclaw", fb: "https://facebook.com/whiteclaw", x: "https://x.com/whiteclaw", web: "https://whiteclaw.com",
      snapshot: [
        { platform: "Facebook",  role: "Light",    comment: "Lifestyle" },
        { platform: "Instagram", role: "Primary",  comment: "Aspirational summer" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "Website",   role: "Primary",  comment: "Flavours & finder" } ],
      themes: { Promotions: 35, Product: 70, Serves: 40, Seasonal: 45, Lifestyle: 75 },
      insight: "White Claw owned the seltzer-summer lane with the **Summer of White Claw** push and new flavour drops, leaning on aspirational, sun-soaked lifestyle creative.",
      sentiment: { positive: 72, neutral: 22, negative: 6 }, freq: { Facebook: 12, Instagram: 22, X: 0 }, score: 8.2,
      creative: { platformNative: 8, culturalRelevance: 9, visualDistinctiveness: 8, strategicClarity: 9, engagementPotential: 8 },
      exec: "Category-defining lifestyle brand — White Claw equals seltzer summer in culture.",
      campaigns: [{ title: "Summer of White Claw", description: "Seasonal lifestyle platform + flavour drops." }],
      whitespace: "Heavy seasonal skew leaves shoulder months quiet.", rec: "Year-round occasions are open territory.",
      signalMatch: true, signalNote: "Found a **Summer of White Claw** flavour-drop campaign dated 8 June on Instagram.", signalLink: "https://instagram.com/whiteclaw" }),
    demoCard({ name: "Truly", handle: "@trulyseltzer", color: "#E84393", parent: "hunters",
      ig: "https://instagram.com/trulyseltzer", fb: "https://facebook.com/trulyhardseltzer", x: "https://x.com/trulyseltzer", web: "https://trulyseltzer.com",
      snapshot: [
        { platform: "Facebook",  role: "Light",    comment: "Flavour-led" },
        { platform: "Instagram", role: "Primary",  comment: "Bright, bold" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "Website",   role: "Light",    comment: "Range & locator" } ],
      themes: { Promotions: 50, Product: 78, Serves: 35, Seasonal: 35, Lifestyle: 55 },
      insight: "Truly chased flavour innovation, with the **Truly Unruly** higher-ABV line and bright creator content courting a younger seltzer drinker.",
      sentiment: { positive: 66, neutral: 26, negative: 8 }, freq: { Facebook: 12, Instagram: 20, X: 0 }, score: 7.6,
      creative: { platformNative: 8, culturalRelevance: 7, visualDistinctiveness: 8, strategicClarity: 7, engagementPotential: 7 },
      exec: "Flavour-first challenger — innovating hard to close the gap on White Claw.",
      campaigns: [{ title: "Truly Unruly", description: "Higher-ABV line extension push." }],
      whitespace: "Brand world less distinctive than White Claw's.", rec: "Truly competes on flavour news, not equity." }),
    demoCard({ name: "High Noon", handle: "@highnoonsunsips", color: "#F39C12", parent: "hunters",
      ig: "https://instagram.com/highnoonsunsips", fb: "https://facebook.com/highnoon", x: "https://x.com/highnoonsunsips", web: "https://highnoonspirits.com",
      snapshot: [
        { platform: "Facebook",  role: "Light",    comment: "Sun-soaked" },
        { platform: "Instagram", role: "Primary",  comment: "Real-vodka story" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "Website",   role: "Light",    comment: "Flavours" } ],
      themes: { Promotions: 40, Product: 72, Serves: 45, Seasonal: 50, Lifestyle: 70 },
      insight: "High Noon rode its momentum as the fastest-growing RTD, with the **Vodka, not malt** message and beach-lifestyle creative fuelling premium seltzer appeal.",
      sentiment: { positive: 74, neutral: 20, negative: 6 }, freq: { Facebook: 10, Instagram: 18, X: 0 }, score: 7.8,
      creative: { platformNative: 8, culturalRelevance: 8, visualDistinctiveness: 8, strategicClarity: 9, engagementPotential: 7 },
      exec: "Premium-RTD momentum brand — a clear 'real vodka' differentiator vs malt-based seltzers.",
      campaigns: [{ title: "Vodka, not malt", description: "Premium-ingredient differentiation message." }],
      whitespace: "Lower posting frequency than rivals.", rec: "Strong proposition, under-amplified — out-posting is winnable." }),
    demoCard({ name: "Angry Orchard", handle: "@angryorchard", color: "#A93226", parent: "hunters",
      ig: "https://instagram.com/angryorchard", fb: "https://facebook.com/angryorchard", x: "https://x.com/angryorchard", web: "https://angryorchard.com",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Orchard heritage" },
        { platform: "Instagram", role: "Primary",  comment: "Crisp apple craft" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "Website",   role: "Light",    comment: "Ciders & visits" } ],
      themes: { Promotions: 40, Product: 68, Serves: 40, Seasonal: 40, Lifestyle: 60 },
      insight: "Angry Orchard held the craft-cider lane with **orchard provenance** storytelling and crisp-apple seasonal creative, defending share as seltzers crowd the space.",
      sentiment: { positive: 70, neutral: 24, negative: 6 }, freq: { Facebook: 14, Instagram: 16, X: 0 }, score: 7.3,
      creative: { platformNative: 7, culturalRelevance: 7, visualDistinctiveness: 8, strategicClarity: 8, engagementPotential: 7 },
      exec: "Heritage craft-cider play — provenance and quality cues over trend-chasing.",
      campaigns: [{ title: "Orchard provenance", description: "Craft and origin storytelling." }],
      whitespace: "Cider losing share of voice to seltzers.", rec: "Craft-provenance is a defensible, ownable angle." }),
  ],
  beauty: [
    demoCard({ name: "e.l.f. Cosmetics", handle: "@elfcosmetics", color: "#2ECC71", parent: "beauty",
      ig: "https://instagram.com/elfcosmetics", fb: "https://facebook.com/elfcosmetics", x: "https://x.com/elfcosmetics", tiktok: "@elfyeah", web: "https://elfcosmetics.com",
      snapshot: [
        { platform: "Facebook",  role: "Light",    comment: "Promos" },
        { platform: "Instagram", role: "Primary",  comment: "Affordable dupes" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "TikTok",    role: "Primary",  comment: "Viral, Gen-Z native" },
        { platform: "Website",   role: "Primary",  comment: "Shop & Beauty Squad" } ],
      themes: { Promotions: 60, Product: 75, Serves: 20, Seasonal: 30, Lifestyle: 55 },
      insight: "e.l.f. dominated value-beauty culture, with TikTok-native content and the **Power Grip** hero range turning affordability into a viral engine.",
      sentiment: { positive: 76, neutral: 18, negative: 6 }, freq: { Facebook: 10, Instagram: 22, X: 0, TikTok: 30 }, score: 8.6,
      creative: { platformNative: 10, culturalRelevance: 9, visualDistinctiveness: 8, strategicClarity: 8, engagementPotential: 9 },
      exec: "The TikTok-native value champion — e.l.f. weaponises affordability and creator culture.",
      campaigns: [{ title: "Power Grip", description: "Hero primer range fuelling viral demos." }],
      whitespace: "Prestige credibility ceiling vs luxury houses.", rec: "e.l.f.'s creator-volume model is the value-beauty benchmark.",
      signalMatch: true, signalNote: "Found a **Power Grip** creator-led TikTok push dated 11 June.", signalLink: "https://instagram.com/elfcosmetics" }),
    demoCard({ name: "Rare Beauty", handle: "@rarebeauty", color: "#D4498F", parent: "beauty",
      ig: "https://instagram.com/rarebeauty", fb: "https://facebook.com/rarebeauty", x: "https://x.com/rarebeauty", tiktok: "@rarebeauty", web: "https://rarebeauty.com",
      snapshot: [
        { platform: "Facebook",  role: "Light",    comment: "Brand world" },
        { platform: "Instagram", role: "Primary",  comment: "Soft, inclusive" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "TikTok",    role: "Primary",  comment: "Hero-product virality" },
        { platform: "Website",   role: "Primary",  comment: "Shop & mental health" } ],
      themes: { Promotions: 35, Product: 78, Serves: 20, Seasonal: 25, Lifestyle: 70 },
      insight: "Rare Beauty paired the viral **Soft Pinch** blush with its **Rare Impact** mental-health mission, blending hero-product demand with genuine brand purpose.",
      sentiment: { positive: 80, neutral: 15, negative: 5 }, freq: { Facebook: 8, Instagram: 20, X: 0, TikTok: 26 }, score: 8.7,
      creative: { platformNative: 9, culturalRelevance: 9, visualDistinctiveness: 9, strategicClarity: 9, engagementPotential: 9 },
      exec: "Purpose plus product — Selena-founded equity and a true hero SKU make Rare a benchmark.",
      campaigns: [{ title: "Soft Pinch", description: "Viral liquid-blush hero product." }, { title: "Rare Impact", description: "Mental-health mission platform." }],
      whitespace: "Narrow range vs full-line houses.", rec: "Purpose-led storytelling is the model to study." }),
    demoCard({ name: "Fenty Beauty", handle: "@fentybeauty", color: "#8E44AD", parent: "beauty",
      ig: "https://instagram.com/fentybeauty", fb: "https://facebook.com/fentybeauty", x: "https://x.com/fentybeauty", tiktok: "@fentybeauty", web: "https://fentybeauty.com",
      snapshot: [
        { platform: "Facebook",  role: "Light",    comment: "Launches" },
        { platform: "Instagram", role: "Primary",  comment: "Inclusive, bold" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "TikTok",    role: "Primary",  comment: "Shade-match content" },
        { platform: "Website",   role: "Primary",  comment: "Shop & shades" } ],
      themes: { Promotions: 45, Product: 80, Serves: 20, Seasonal: 30, Lifestyle: 60 },
      insight: "Fenty leaned on its **inclusivity** founding story and the **Pro Filt'r** franchise, using shade-range breadth as both product and cultural statement.",
      sentiment: { positive: 74, neutral: 20, negative: 6 }, freq: { Facebook: 10, Instagram: 20, X: 0, TikTok: 22 }, score: 8.2,
      creative: { platformNative: 8, culturalRelevance: 9, visualDistinctiveness: 9, strategicClarity: 8, engagementPotential: 8 },
      exec: "Inclusivity pioneer — Rihanna-founded equity and shade leadership keep Fenty culturally central.",
      campaigns: [{ title: "Pro Filt'r", description: "Flagship complexion franchise." }],
      whitespace: "Premium price limits mass-value reach.", rec: "Inclusivity leadership is the cultural benchmark." }),
    demoCard({ name: "Glossier", handle: "@glossier", color: "#E8B4B8", parent: "beauty",
      ig: "https://instagram.com/glossier", fb: "https://facebook.com/glossier", x: "https://x.com/glossier", tiktok: "@glossier", web: "https://glossier.com",
      snapshot: [
        { platform: "Facebook",  role: "Light",    comment: "Minimal" },
        { platform: "Instagram", role: "Primary",  comment: "Dewy, editorial" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "TikTok",    role: "Light",    comment: "Routine content" },
        { platform: "Website",   role: "Primary",  comment: "DTC shop" } ],
      themes: { Promotions: 30, Product: 72, Serves: 25, Seasonal: 25, Lifestyle: 78 },
      insight: "Glossier held its 'skin-first' aesthetic, with the **Balm Dotcom** and **You** fragrance anchoring a community-led, editorial brand world.",
      sentiment: { positive: 72, neutral: 22, negative: 6 }, freq: { Facebook: 8, Instagram: 18, X: 0, TikTok: 12 }, score: 7.7,
      creative: { platformNative: 8, culturalRelevance: 8, visualDistinctiveness: 9, strategicClarity: 8, engagementPotential: 7 },
      exec: "Aesthetic-led DTC pioneer — distinctive minimal world, lighter on trend-volume.",
      campaigns: [{ title: "Balm Dotcom", description: "Cult hero-product franchise." }],
      whitespace: "Lower posting cadence than viral-led rivals.", rec: "Distinctive aesthetic, under-amplified — frequency is winnable." }),
  ],
};
const DEMO_DATA_UK = {
  qsr: [
    demoCard({ name: "McDonald's UK", handle: "@mcdonaldsuk", color: "#FFC72C", parent: "qsr",
      ig: "https://instagram.com/mcdonaldsuk", fb: "https://facebook.com/mcdonaldsuk", x: "https://x.com/mcdonaldsuk", tiktok: "@mcdonaldsuk", web: "https://mcdonalds.com/gb",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Value & moments" },
        { platform: "Instagram", role: "Primary",  comment: "Menu & culture" },
        { platform: "X",         role: "Primary",  comment: "Topical Britishness" },
        { platform: "TikTok",    role: "Primary",  comment: "Trend-native" },
        { platform: "Website",   role: "Primary",  comment: "App & rewards" } ],
      themes: { Promotions: 68, Product: 65, Serves: 25, Seasonal: 40, Lifestyle: 50 },
      insight: "McDonald's UK blended value with very British cultural moments, leaning on the **Monopoly** return teasers and app-led deals to dominate share of voice.",
      sentiment: { positive: 62, neutral: 28, negative: 10 }, freq: { Facebook: 20, Instagram: 22, X: 26, TikTok: 20 }, score: 8.2,
      creative: { platformNative: 9, culturalRelevance: 9, visualDistinctiveness: 8, strategicClarity: 8, engagementPotential: 8 },
      exec: "Mass scale plus local culture — McDonald's UK owns the high-frequency, high-relevance feed.",
      campaigns: [{ title: "Monopoly", description: "Returning gamified promotion driving footfall." }],
      whitespace: "Premium cues light amid value noise.", rec: "Craft positioning is open against the value play.",
      signalMatch: true, signalNote: "Found **Monopoly** return teasers dated 10 June across Instagram and TikTok.", signalLink: "https://instagram.com/mcdonaldsuk" }),
    demoCard({ name: "Greggs", handle: "@greggs_official", color: "#00539F", parent: "qsr",
      ig: "https://instagram.com/greggs_official", fb: "https://facebook.com/Greggs", x: "https://x.com/GreggsOfficial", tiktok: "@greggs", web: "https://greggs.co.uk",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Cult fan culture" },
        { platform: "Instagram", role: "Primary",  comment: "Bakes & banter" },
        { platform: "X",         role: "Primary",  comment: "Witty national-treasure" },
        { platform: "TikTok",    role: "Primary",  comment: "Viral sausage-roll" },
        { platform: "Website",   role: "Light",    comment: "Menu & rewards" } ],
      themes: { Promotions: 55, Product: 70, Serves: 25, Seasonal: 35, Lifestyle: 60 },
      insight: "Greggs played its national-treasure status to the hilt, with the **summer menu** drop and tongue-in-cheek content turning everyday bakes into cultural events.",
      sentiment: { positive: 82, neutral: 14, negative: 4 }, freq: { Facebook: 18, Instagram: 20, X: 22, TikTok: 24 }, score: 8.8,
      creative: { platformNative: 9, culturalRelevance: 10, visualDistinctiveness: 9, strategicClarity: 9, engagementPotential: 9 },
      exec: "Cultural icon punching far above spend — Greggs is the UK distinctiveness benchmark.",
      campaigns: [{ title: "Summer menu", description: "Seasonal range drop with viral social." }],
      whitespace: "Premium/health perceptions are a soft spot.", rec: "Greggs' cultural fluency is the model to study.",
      signalMatch: true, signalNote: "Found a **summer menu** launch dated 6 June that went viral on TikTok.", signalLink: "https://instagram.com/greggs_official" }),
    demoCard({ name: "Burger King UK", handle: "@burgerkinguk", color: "#D62300", parent: "qsr",
      ig: "https://instagram.com/burgerkinguk", fb: "https://facebook.com/burgerkinguk", x: "https://x.com/BurgerKingUK", tiktok: "@burgerkinguk", web: "https://burgerking.co.uk",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Challenger value" },
        { platform: "Instagram", role: "Primary",  comment: "Flame-grill craft" },
        { platform: "X",         role: "Primary",  comment: "Cheeky jabs" },
        { platform: "TikTok",    role: "Light",    comment: "Occasional trends" },
        { platform: "Website",   role: "Light",    comment: "App & deals" } ],
      themes: { Promotions: 80, Product: 68, Serves: 35, Seasonal: 20, Lifestyle: 20 },
      insight: "Burger King UK ran its challenger playbook, with app-only **Whopper** deals and cheeky competitive jabs driving a price-led, reactive June.",
      sentiment: { positive: 58, neutral: 30, negative: 12 }, freq: { Facebook: 16, Instagram: 16, X: 18, TikTok: 8 }, score: 7.2,
      creative: { platformNative: 7, culturalRelevance: 7, visualDistinctiveness: 7, strategicClarity: 7, engagementPotential: 7 },
      exec: "Challenger value play — strong on app deals and wit, lighter on cultural depth than Greggs.",
      campaigns: [{ title: "App-only Whopper deals", description: "Discount mechanic driving app installs." }],
      whitespace: "Discount-heavy posture risks equity.", rec: "Compete on distinctiveness, not just price." }),
    demoCard({ name: "KFC UK", handle: "@kfc_uki", color: "#E4002B", parent: "qsr",
      ig: "https://instagram.com/kfc_uki", fb: "https://facebook.com/KFCUKI", x: "https://x.com/KFC_UKI", tiktok: "@kfc.uki", web: "https://kfc.co.uk",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Value buckets" },
        { platform: "Instagram", role: "Primary",  comment: "Crave-led" },
        { platform: "X",         role: "Light",    comment: "Banter" },
        { platform: "TikTok",    role: "Primary",  comment: "Gravy/culture trends" },
        { platform: "Website",   role: "Primary",  comment: "App & deals" } ],
      themes: { Promotions: 72, Product: 65, Serves: 30, Seasonal: 25, Lifestyle: 45 },
      insight: "KFC UK leaned on crave-led value, with the **£5.99 boxmeal** push and music-culture content keeping its young, value-seeking base engaged.",
      sentiment: { positive: 64, neutral: 26, negative: 10 }, freq: { Facebook: 18, Instagram: 18, X: 12, TikTok: 22 }, score: 7.8,
      creative: { platformNative: 8, culturalRelevance: 8, visualDistinctiveness: 7, strategicClarity: 8, engagementPotential: 8 },
      exec: "Value-and-culture play — KFC UK ties affordability to youth music culture.",
      campaigns: [{ title: "£5.99 boxmeal", description: "Anchor value mechanic for the period." }],
      whitespace: "Distinctiveness lower than Greggs' cultural edge.", rec: "Cultural ownership is contestable here." }),
  ],
  beauty: [
    demoCard({ name: "Charlotte Tilbury", handle: "@charlottetilbury", color: "#C9A24B", parent: "beauty",
      ig: "https://instagram.com/charlottetilbury", fb: "https://facebook.com/charlottetilbury", x: "https://x.com/CTilburyMakeup", tiktok: "@charlottetilbury", web: "https://charlottetilbury.com",
      snapshot: [
        { platform: "Facebook",  role: "Light",    comment: "Launches" },
        { platform: "Instagram", role: "Primary",  comment: "Glamour, hero SKUs" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "TikTok",    role: "Primary",  comment: "Pillow Talk virality" },
        { platform: "Website",   role: "Primary",  comment: "Shop & magic" } ],
      themes: { Promotions: 40, Product: 80, Serves: 20, Seasonal: 30, Lifestyle: 65 },
      insight: "Charlotte Tilbury leaned on icon-product gravity, with the **Pillow Talk** franchise and **Flawless Filter** anchoring a glamorous, aspirational June.",
      sentiment: { positive: 78, neutral: 17, negative: 5 }, freq: { Facebook: 10, Instagram: 22, X: 0, TikTok: 24 }, score: 8.6,
      creative: { platformNative: 9, culturalRelevance: 8, visualDistinctiveness: 9, strategicClarity: 9, engagementPotential: 9 },
      exec: "Icon-product luxury — Charlotte Tilbury turns hero SKUs into self-sustaining cultural demand.",
      campaigns: [{ title: "Pillow Talk", description: "Flagship franchise driving repeat virality." }],
      whitespace: "Premium price caps value-seeker reach.", rec: "Icon-product strategy is the prestige benchmark.",
      signalMatch: true, signalNote: "Found a **Flawless Filter** creator push dated 9 June on TikTok and Instagram.", signalLink: "https://instagram.com/charlottetilbury" }),
    demoCard({ name: "Rimmel London", handle: "@rimmellondonuk", color: "#E4002B", parent: "beauty",
      ig: "https://instagram.com/rimmellondonuk", fb: "https://facebook.com/rimmellondon", x: "https://x.com/rimmellondon", tiktok: "@rimmellondon", web: "https://rimmellondon.com",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Mass value" },
        { platform: "Instagram", role: "Primary",  comment: "London edginess" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "TikTok",    role: "Primary",  comment: "Affordable trends" },
        { platform: "Website",   role: "Light",    comment: "Range" } ],
      themes: { Promotions: 60, Product: 72, Serves: 20, Seasonal: 30, Lifestyle: 50 },
      insight: "Rimmel played its 'London look' heritage at a value price, with the **Wonder'Extension** mascara push and street-style creator content driving accessibility.",
      sentiment: { positive: 66, neutral: 26, negative: 8 }, freq: { Facebook: 14, Instagram: 18, X: 0, TikTok: 20 }, score: 7.5,
      creative: { platformNative: 8, culturalRelevance: 7, visualDistinctiveness: 7, strategicClarity: 7, engagementPotential: 7 },
      exec: "Heritage value brand — 'London look' equity at an accessible price point.",
      campaigns: [{ title: "Wonder'Extension", description: "Hero mascara launch." }],
      whitespace: "Distinctiveness fading vs viral-native rivals.", rec: "Heritage needs a modern creator engine." }),
    demoCard({ name: "No7", handle: "@no7uk", color: "#00A3A1", parent: "beauty",
      ig: "https://instagram.com/no7uk", fb: "https://facebook.com/No7UK", x: "https://x.com/No7UK", tiktok: "@no7", web: "https://no7beauty.com",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Skincare-science" },
        { platform: "Instagram", role: "Primary",  comment: "Trusted, results-led" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "TikTok",    role: "Light",    comment: "Serum education" },
        { platform: "Website",   role: "Primary",  comment: "Shop & advice" } ],
      themes: { Promotions: 50, Product: 78, Serves: 25, Seasonal: 25, Lifestyle: 45 },
      insight: "No7 leaned on science-backed trust, with the **Future Renew** serum and clinical-proof messaging anchoring a mature, results-led skincare-beauty audience.",
      sentiment: { positive: 72, neutral: 22, negative: 6 }, freq: { Facebook: 14, Instagram: 16, X: 0, TikTok: 10 }, score: 7.7,
      creative: { platformNative: 7, culturalRelevance: 7, visualDistinctiveness: 7, strategicClarity: 9, engagementPotential: 7 },
      exec: "Science-and-trust positioning — Boots-backed credibility with a results promise.",
      campaigns: [{ title: "Future Renew", description: "Hero serum with clinical-proof claims." }],
      whitespace: "Skews mature; lighter youth/creator pull.", rec: "Proof-led trust is a credible, ownable angle." }),
    demoCard({ name: "Max Factor", handle: "@maxfactor", color: "#7D3C98", parent: "beauty",
      ig: "https://instagram.com/maxfactor", fb: "https://facebook.com/maxfactor", x: "https://x.com/maxfactor", tiktok: "@maxfactor", web: "https://maxfactor.com",
      snapshot: [
        { platform: "Facebook",  role: "Primary",  comment: "Glamour heritage" },
        { platform: "Instagram", role: "Primary",  comment: "Make-up artistry" },
        { platform: "X",         role: "Inactive", comment: "" },
        { platform: "TikTok",    role: "Light",    comment: "Foundation demos" },
        { platform: "Website",   role: "Light",    comment: "Range" } ],
      themes: { Promotions: 55, Product: 74, Serves: 20, Seasonal: 28, Lifestyle: 48 },
      insight: "Max Factor played its 'make-up artist' heritage, with the **Facefinity** complexion franchise and glamour-led creative targeting a classic beauty buyer.",
      sentiment: { positive: 64, neutral: 28, negative: 8 }, freq: { Facebook: 14, Instagram: 16, X: 0, TikTok: 8 }, score: 7.2,
      creative: { platformNative: 7, culturalRelevance: 6, visualDistinctiveness: 7, strategicClarity: 8, engagementPotential: 6 },
      exec: "Heritage artistry brand — strong product franchise, lighter cultural and creator presence.",
      campaigns: [{ title: "Facefinity", description: "Flagship complexion franchise." }],
      whitespace: "Low creator/cultural relevance vs rivals.", rec: "Heritage needs a contemporary social engine." }),
  ],
};

/* Returns a deep copy of demo cards for the brand's category in the given
   market (US/UK if available, else South Africa), or null. */
function loadDemoCompetitors(brandSel, market) {
  const cat = BRANDS[brandSel] && BRANDS[brandSel].category;
  const byMarket = market === "us" ? DEMO_DATA_US : market === "uk" ? DEMO_DATA_UK : null;
  const set = (byMarket && byMarket[cat]) || DEMO_DATA[cat];
  if (!set) return null;
  return set.map(c => ({ ...c, posts: [...c.posts], snapshot: c.snapshot.map(s => ({ ...s })), themes: c.themes.map(t => ({ ...t })) }));
}
